DROP VIEW IF EXISTS V_PERSONS_FEMALE,
                    V_PERSONS_MALE,
                    V_GENERATED_DATES,
                    V_SYMMETRIC_UNION,
                    V_PRICE_WITH_DISCOUNT;
DROP MATERIALIZED VIEW IF EXISTS MV_DMITRIY_VISITS_AND_EATS;
