ALTER TABLE PERSON_DISCOUNTS
ADD CONSTRAINT CH_NN_PERSON_ID CHECK (PERSON_ID IS NOT NULL),
ADD CONSTRAINT CH_NN_PIZZERIA_ID CHECK (PIZZERIA_ID IS NOT NULL),
ADD CONSTRAINT CH_NN_DISCOUNT CHECK (DISCOUNT IS NOT NULL),
ALTER COLUMN DISCOUNT SET DEFAULT 0,
ADD CONSTRAINT CH_RANGE_DISCOUNT CHECK (DISCOUNT <= 100 AND DISCOUNT >= 0);
