CREATE INDEX IF NOT EXISTS IDX_MENU_PIZZERIA_ID ON MENU (PIZZERIA_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSON_ORDER_MENU_ID ON PERSON_ORDER (MENU_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSON_ORDER_PERSON_ID ON PERSON_ORDER (PERSON_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSON_VISITS_PERSON_ID ON PERSON_VISITS (PERSON_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSON_VISITS_PIZZERIA_ID ON PERSON_VISITS (PIZZERIA_ID);
