SELECT 	NAME,
		PIZZA_NAME,
		PRICE,
		ROUND(PRICE * (1 - DISCOUNT / 100)) AS DISCOUNT_PRICE
FROM PERSON P
JOIN PERSON_ORDER PO
ON PO.PERSON_ID = P.ID
JOIN MENU M
ON M.ID = PO.MENU_ID
JOIN PERSON_DISCOUNTS PD
ON PD.PERSON_ID = PO.PERSON_ID
ORDER BY 1, 2;
