SELECT (PV.PERSON_NAME) AS PERSON_NAME,
    (PV.PIZZERIA_NAME) AS PIZZERIA_NAME
FROM (SELECT PERSON.NAME AS PERSON_NAME, PIZZERIA.NAME AS PIZZERIA_NAME, PERSON_VISITS.*
      FROM PERSON, PIZZERIA, PERSON_VISITS
      WHERE PERSON_VISITS.PERSON_ID = PERSON.ID AND PERSON_VISITS.PIZZERIA_ID = PIZZERIA.id AND PERSON_VISITS.VISIT_DATE BETWEEN '2022-01-07' AND '2022-01-09') AS PV
ORDER BY PERSON_NAME, PIZZERIA_NAME DESC
