SELECT DISTINCT M.PIZZA_NAME,
       M.PRICE,
       PZ.NAME PIZZERIA_NAME,
       PV.VISIT_DATE
FROM PERSON_VISITS PV
    INNER JOIN PERSON P ON P.ID = PV.PERSON_ID
    INNER JOIN PIZZERIA PZ ON PV.PIZZERIA_ID = PZ.ID
    INNER JOIN MENU M ON M.PIZZERIA_ID = PZ.ID
WHERE M.PRICE BETWEEN 800 AND 1000 AND P.NAME = 'Kate'
ORDER BY 1, 2, 3;
