INSERT INTO PERSON_VISITS
VALUES ((SELECT MAX(ID) FROM PERSON_VISITS) + 1,
        (SELECT ID FROM PERSON WHERE NAME = 'Dmitriy'),
        (SELECT MIN(PZ.ID) FROM MENU M
            INNER JOIN PIZZERIA PZ ON M.PIZZERIA_ID = PZ.ID
            WHERE PRICE < 800 AND PZ.NAME != 'Papa Johns'),
        '2022-01-08'::DATE);
REFRESH MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS;
