DROP FUNCTION IF EXISTS FNC_PERSONS_FEMALE();
DROP FUNCTION IF EXISTS FNC_PERSONS_MALE();

CREATE OR REPLACE FUNCTION FNC_PERSONS(PGENDER VARCHAR DEFAULT 'female')
    RETURNS TABLE
    (
        NAME VARCHAR
    ) AS
$PERSON_AUDIT$
    SELECT NAME
    FROM PERSON
    WHERE GENDER = PGENDER
$PERSON_AUDIT$ LANGUAGE SQL;

SELECT *
FROM FNC_PERSONS(PGENDER := 'male');

SELECT *
FROM FNC_PERSONS();
