CREATE SEQUENCE IF NOT EXISTS SEQ_PERSON_DISCOUNTS START 1;

SELECT SETVAL('SEQ_PERSON_DISCOUNTS', (SELECT MAX(ID) FROM PERSON_DISCOUNTS));

ALTER TABLE PERSON_DISCOUNTS
ALTER COLUMN ID SET DEFAULT NEXTVAL('SEQ_PERSON_DISCOUNTS');
