SELECT P.NAME PERSON_NAME1,
       P2.NAME PERSON_NAME2,
       P.ADDRESS COMMON_ADDRESS
FROM PERSON P INNER JOIN PERSON P2 ON P.ADDRESS = P2.ADDRESS
WHERE P.ID > P2.ID
ORDER BY PERSON_NAME1, PERSON_NAME2, COMMON_ADDRESS;
