WITH PIZZA1 AS (SELECT PZ.ID, M.PIZZA_NAME, PZ.NAME, M.PRICE
                FROM MENU M
                    INNER JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID),
    PIZZA2 AS (SELECT * FROM PIZZA1)

SELECT DISTINCT P1.PIZZA_NAME,
                P1.NAME PIZZERIA_NAME_1,
                P2.NAME PIZZERIA_NAME_2,
                P1.PRICE
FROM PIZZA1 P1
    INNER JOIN MENU M ON M.PIZZERIA_ID = P1.ID, PIZZA2 P2
WHERE P1.PIZZA_NAME = P2.PIZZA_NAME AND
	  P1.PRICE = P2.PRICE AND
	  P1.NAME < P2.NAME
ORDER BY 1;
