CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_UPDATE_AUDIT() RETURNS TRIGGER AS
$PERSON_AUDIT$
BEGIN
    IF (TG_OP = 'UPDATE') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'U', OLD.*;
    END IF;
    RETURN NULL;
END;
$PERSON_AUDIT$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PERSON_UPDATE_AUDIT
    AFTER UPDATE
    ON PERSON
    FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_UPDATE_AUDIT();

UPDATE PERSON SET NAME = 'Bulat' WHERE ID = 10;
UPDATE PERSON SET NAME = 'Damir' WHERE ID = 10;
