WITH FEMALE_ORDERS AS (SELECT P.NAME, M.PIZZA_NAME
                        FROM PERSON_ORDER PO
                            INNER JOIN PERSON P ON P.ID = PO.PERSON_ID
                            INNER JOIN MENU M ON PO.MENU_ID = M.ID
                        WHERE P.GENDER = 'female')
SELECT FEMALE_ORDERS.NAME
FROM FEMALE_ORDERS
WHERE FEMALE_ORDERS.PIZZA_NAME = 'cheese pizza'
INTERSECT
SELECT FEMALE_ORDERS.NAME
FROM FEMALE_ORDERS
WHERE FEMALE_ORDERS.PIZZA_NAME = 'pepperoni pizza'
ORDER BY 1;
