CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT() RETURNS TRIGGER AS
$PERSON_AUDIT$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'D', OLD.*;
    END IF;
    RETURN NULL;
END;
$PERSON_AUDIT$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PERSON_DELETE_AUDIT
    AFTER DELETE
    ON PERSON
    FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_DELETE_AUDIT();

DELETE FROM PERSON WHERE ID = 10;
