CREATE TABLE IF NOT EXISTS PERSON_DISCOUNTS (
	ID BIGINT PRIMARY KEY,
	PERSON_ID BIGINT,
	PIZZERIA_ID BIGINT,
	DISCOUNT REAL,
	CONSTRAINT FK_PERSON_DISCOUNTS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
	CONSTRAINT FK_PERSON_DISCOUNTS_PIZZERIA_ID FOREIGN KEY (PIZZERIA_ID) REFERENCES PIZZERIA (ID)
)
