SELECT M.PIZZA_NAME, PZ.NAME PIZZERIA_NAME, M.PRICE
FROM MENU M INNER JOIN PIZZERIA PZ ON M.PIZZERIA_ID = PZ.ID
WHERE M.PIZZA_NAME = 'mushroom pizza' OR M.PIZZA_NAME = 'pepperoni pizza'
ORDER BY 1, 2;
