CREATE OR REPLACE FUNCTION FUNC_MINIMUM(
    VARIADIC ARR NUMERIC[]
)
RETURNS NUMERIC AS
$PERSON_AUDIT$
    SELECT MIN($1[I])
    FROM GENERATE_SUBSCRIPTS($1, 1) G(I);
$PERSON_AUDIT$ LANGUAGE SQL;

SELECT FUNC_MINIMUM(VARIADIC ARR => ARRAY [10.0, -1.0, 5.0, 4.4]);
