SELECT PZ.NAME PIZZERIA_NAME
FROM PERSON_VISITS PV
    INNER JOIN PERSON P ON PV.PERSON_ID = P.ID
    INNER JOIN PIZZERIA PZ ON PZ.ID = PV.PIZZERIA_ID
    LEFT JOIN PERSON_ORDER PO ON PV.VISIT_DATE = PO.ORDER_DATE
WHERE P.NAME = 'Andrey' AND PO.ORDER_DATE IS NULL
ORDER BY 1;
