WITH male AS (
    SELECT PZ.NAME PIZZERIA_NAME
    FROM PIZZERIA PZ
        JOIN PERSON_VISITS PV ON PZ.ID = PV.PIZZERIA_ID
        JOIN PERSON P ON P.ID = PV.PERSON_ID
    WHERE P.GENDER = 'male'),
    female AS (
    SELECT PZ.NAME PIZZERIA_NAME
    FROM PIZZERIA PZ
        JOIN PERSON_VISITS PV ON PZ.ID = PV.PIZZERIA_ID
        JOIN PERSON P ON P.ID = PV.PERSON_ID
    WHERE P.GENDER = 'female')
(SELECT * FROM male
          EXCEPT ALL
          SELECT * FROM female)
UNION ALL
(SELECT * FROM female
          EXCEPT ALL
          SELECT * FROM male)
ORDER BY 1;
