INSERT INTO PERSON_DISCOUNTS
SELECT ROW_NUMBER() OVER () AS ID,
	PERSON_ID,
	PIZZERIA_ID,
	CASE
		WHEN VISITS = 1 THEN 10.5
		WHEN VISITS = 2 THEN 22
		ELSE 30
	END AS DISCOUNT
FROM (SELECT 	PERSON_ID,
	  			PIZZERIA_ID,
	  			COUNT( PERSON_ID) AS VISITS
	  FROM PERSON_ORDER PO
	  JOIN MENU M ON M.ID = PO.MENU_ID
	  GROUP BY PERSON_ID, PIZZERIA_ID
	  ORDER BY 1, 2
	 ) AS TMP
ON CONFLICT DO NOTHING;
