WITH ALL_COST AS (SELECT MENU_ID,
			COUNT(MENU_ID) AS ORDERS,
			SUM(PRICE) AS SUMM,
			MAX(PRICE) AS PRICE
			FROM PERSON_ORDER PO
			JOIN MENU M
			ON PO.MENU_ID = M.ID
			GROUP BY 1
		   ),
	 PIZZERIAS_PAYMENTS AS (SELECT PZ.NAME,
			SUM(ORDERS) AS COUNT_OF_ORDERS,
			SUM(SUMM) AS SUMM,
			MAX(AC.PRICE) AS MAX_PRICE,
			MIN(AC.PRICE) AS MIN_PRICE
			FROM MENU M JOIN ALL_COST AC
			ON AC.MENU_ID = M.ID
			JOIN PIZZERIA PZ ON M.PIZZERIA_ID = PZ.ID
			GROUP BY PZ.NAME
		   )
SELECT	NAME,
		COUNT_OF_ORDERS,
		ROUND(SUMM/COUNT_OF_ORDERS, 2) AS AVERAGE_PRICE,
		MAX_PRICE,
		MIN_PRICE
FROM PIZZERIAS_PAYMENTS
ORDER BY 1;
