SELECT PR.NAME PERSON_NAME, M.PIZZA_NAME PIZZA_NAME, PZ.NAME PIZZERIA_NAME
FROM PERSON_ORDER PO INNER JOIN PERSON PR ON PR.ID = PO.PERSON_ID INNER JOIN MENU M ON PO.MENU_ID = M.ID INNER JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID
ORDER BY PERSON_NAME, PIZZA_NAME, PIZZERIA_NAME;
