SELECT DISTINCT PERSON.ID
FROM  PERSON INNER JOIN PERSON_VISITS ON PERSON_VISITS.PERSON_ID = PERSON.ID
WHERE PERSON_VISITS.visit_date BETWEEN '2022-01-06' AND '2022-01-09' or PERSON_VISITS.PIZZERIA_ID = 2
ORDER BY PERSON.ID DESC;
