CREATE VIEW V_PRICE_WITH_DISCOUNT AS (
    SELECT P.NAME,
           M.PIZZA_NAME,
           M.PRICE,
           ROUND(M.PRICE*0.9) DISCOUNT_PRICE

    FROM PERSON_ORDER PO
        INNER JOIN PERSON P ON P.ID = PO.PERSON_ID
        INNER JOIN MENU M ON PO.MENU_ID = M.ID
    ORDER BY 1, 2
);
