SELECT P.NAME
FROM PERSON_ORDER PO
    INNER JOIN PERSON P ON P.ID = PO.PERSON_ID
    INNER JOIN MENU M ON M.ID = PO.MENU_ID
WHERE P.GENDER = 'male' AND (P.ADDRESS = 'Moscow' OR P.ADDRESS = 'Samara') AND (M.PIZZA_NAME = 'pepperoni pizza' OR M.PIZZA_NAME = 'mushroom pizza')
ORDER BY P.NAME DESC;
