CREATE TABLE PERSON_AUDIT (
    CREATED TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TYPE_EVENT CHAR(1) DEFAULT 'I' NOT NULL,
    ROW_ID BIGINT NOT NULL,
    NAME VARCHAR,
    AGE INTEGER,
    GENDER VARCHAR,
    ADDRESS VARCHAR,
    CONSTRAINT CH_TYPE_EVENT CHECK ( TYPE_EVENT = 'I' OR TYPE_EVENT = 'D' OR TYPE_EVENT = 'U' ));

CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT() RETURNS TRIGGER AS
$PERSON_AUDIT$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'I', NEW.*;
    END IF;
    RETURN NULL;
END;
$PERSON_AUDIT$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER TRG_PERSON_INSERT_AUDIT
    AFTER INSERT
    ON PERSON
    FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_INSERT_AUDIT();

INSERT INTO PERSON(ID, NAME, AGE, GENDER, ADDRESS) VALUES (10,'Damir', 22, 'male', 'Irkutsk');
