SELECT DISTINCT PO.ORDER_DATE AS ACTION_DATE, P.NAME AS PERSON_NAME
FROM PERSON_ORDER PO
INNER JOIN PERSON_VISITS PV ON PV.PERSON_ID = PO.PERSON_ID
INNER JOIN PERSON P ON P.ID = PO.PERSON_ID
ORDER BY ACTION_DATE, PERSON_NAME DESC;
