CREATE OR REPLACE FUNCTION FNC_PERSON_VISITS_AND_EATS_ON_DATE(
    PPERSON VARCHAR DEFAULT 'Dmitriy',
    PPRICE NUMERIC DEFAULT 500,
    PDATE DATE DEFAULT '2022-01-08'
)
    RETURNS TABLE
    (
        NAME VARCHAR
    ) AS
$PERSON_AUDIT$
BEGIN
    RETURN QUERY (SELECT PZ.NAME
                  FROM PERSON P
                  INNER JOIN PERSON_ORDER PO ON P.ID = PO.PERSON_ID
                  INNER JOIN PERSON_VISITS PV ON P.ID = PV.PERSON_ID
                  AND PV.VISIT_DATE = PO.ORDER_DATE
                  INNER JOIN MENU M ON M.ID = PO.MENU_ID
                  INNER JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID
                  WHERE P.NAME = PPERSON AND M.PRICE < PPRICE
                  AND PO.ORDER_DATE = PDATE);
END;
$PERSON_AUDIT$ LANGUAGE PLPGSQL;

SELECT * FROM FNC_PERSON_VISITS_AND_EATS_ON_DATE(PPRICE := 800);

SELECT * FROM FNC_PERSON_VISITS_AND_EATS_ON_DATE(PPERSON := 'Anna', PPRICE := 1300, PDATE := '2022-01-01');
