INSERT INTO PERSON_ORDER
SELECT
    generate_series((SELECT MAX(ID) + 1 FROM PERSON_ORDER),
        (SELECT MAX(PERSON_ORDER.ID) + (SELECT MAX(ID) FROM PERSON) FROM PERSON_ORDER, PERSON)),
    generate_series(1, (SELECT MAX(ID) FROM PERSON)),
    (SELECT MIN(ID) FROM MENU WHERE PIZZA_NAME = 'greek pizza'),
    '2022-02-25';
