WITH VISITS AS (SELECT PZ.NAME,
                       COUNT(PV.PIZZERIA_ID) CNT,
                       'visit' ACTION_TYPE
FROM PERSON_VISITS PV
INNER JOIN PIZZERIA PZ ON PZ.ID = PV.PIZZERIA_ID
GROUP BY PZ.NAME),

ORDERS AS (SELECT PZ.NAME,
                  COUNT(M.PIZZERIA_ID) CNT,
                  'order' ACTION_TYPE
FROM PERSON_ORDER PO
INNER JOIN MENU M on M.ID = PO.MENU_ID
INNER JOIN PIZZERIA PZ ON PZ.ID = M.PIZZERIA_ID
GROUP BY PZ.NAME),

ALL_TEMP AS (
(SELECT * FROM VISITS)
UNION ALL
(SELECT * FROM ORDERS)),

TOP AS (SELECT NAME, SUM(CNT) FROM ALL_TEMP GROUP BY NAME ORDER BY 2 DESC LIMIT 3)

SELECT T.NAME, AT.CNT COUNT, AT.ACTION_TYPE
FROM ALL_TEMP AT
INNER JOIN TOP T ON T.NAME = AT.NAME
ORDER BY 3, 2 DESC;
