CREATE MATERIALIZED VIEW MV_DMITRIY_VISITS_AND_EATS AS (
    SELECT PZ.NAME
    FROM PERSON_VISITS PV
        INNER JOIN PERSON P ON P.ID = PV.PERSON_ID
        INNER JOIN PIZZERIA PZ ON PZ.ID = PV.PIZZERIA_ID
        INNER JOIN MENU M on PZ.ID = M.PIZZERIA_ID
    WHERE PV.VISIT_DATE = '2022-01-08' AND P.NAME = 'Dmitriy' AND M.PRICE < 800
);
