DROP TRIGGER IF EXISTS TRG_PERSON_INSERT_AUDIT ON PERSON;
DROP TRIGGER IF EXISTS TRG_PERSON_UPDATE_AUDIT ON PERSON;
DROP TRIGGER IF EXISTS TRG_PERSON_DELETE_AUDIT ON PERSON;

DROP FUNCTION IF EXISTS FNC_TRG_PERSON_INSERT_AUDIT();
DROP FUNCTION IF EXISTS FNC_TRG_PERSON_UPDATE_AUDIT();
DROP FUNCTION IF EXISTS FNC_TRG_PERSON_DELETE_AUDIT();

TRUNCATE TABLE PERSON_AUDIT;

CREATE OR REPLACE FUNCTION FNC_TRG_PERSON_AUDIT() RETURNS TRIGGER AS
$PERSON_AUDIT$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'I', NEW.*;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'U', OLD.*;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO PERSON_AUDIT SELECT NOW(), 'D', OLD.*;
    END IF;
    RETURN NULL;
END;
$PERSON_AUDIT$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_PERSON_AUDIT
    AFTER INSERT OR UPDATE OR DELETE
    ON PERSON
    FOR EACH ROW
EXECUTE FUNCTION FNC_TRG_PERSON_AUDIT();

INSERT INTO PERSON(ID, NAME, AGE, GENDER, ADDRESS)  VALUES (10,'Damir', 22, 'male', 'Irkutsk');
UPDATE PERSON SET NAME = 'Bulat' WHERE ID = 10;
UPDATE PERSON SET NAME = 'Damir' WHERE ID = 10;
DELETE FROM PERSON WHERE ID = 10;
